#ifndef ERRORMESSAGE_H
#define ERRORMESSAGE_H

enum ErrorMessage {
    NO_ERROR,
    SENSOR_NOT_CONNECTED,
    SENSOR_CONNECTION_FAIL,
    ROBOT_CONNECTION_FAIL,
    ROBOT_NOT_CONNECTED,
    FILE_NOT_EXISTS,
};

#endif // ERRORMESSAGE_H
